name: QA Portal Services

on:
  push:
    branches: 
      - 'feature/**'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      working-directory: ./qa-portal-services
      run: mvn clean install
