name: QA Portal Angular Testing

on:
  push:
    branches: 
      - feature/github-actions

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm --prefix qa-portal-angular run build -- --prod
      - name: Test
        run: npm --prefix qa-portal-angular test -- --configuration=ci


